openapi: 3.0.0

info:
  title: Universal Key-Value Store RESTful API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1

servers:
  - url: http://api.unumdb.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.unumdb.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  # Single Entry API:
  /one/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          minimum: 1
      - name: col
        in: query
        schema:
          type: string
      - name: field
        in: query
        schema:
          type: string

    put:
      summary: Inserts or updates a single key-value pair
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Returns nothing
